### PR TITLE
Tests and fixes for project routes

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler depends on praekelt/seed-auth-js#16, otherwise ready for review.

**Comment by justinvdm** [comment]
@rudigiesler should be ready for review now

**Comment by rudigiesler** [comment]
For the project endpoint tests, I've noticed a few `it('....')` descriptions with no actual test. Is this intentional?

**Comment by rudigiesler** [comment]
Otherwise looks good to me.

**Comment by justinvdm** [comment]
@rudigiesler yep, they're stubs for things we can't properly test until we have working project storage and retrieval. We could just stub them for now, but these tests are meant to be end-to-end tests, so thought it'd defeat the point.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
