### PR TITLE
Remove /user/permissions/ endpoint

### PR DESCRIPTION
**Pull request by justinvdm**
Numi's API won't be needing this, at least not initially.

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
Is there documentation that also needs to be removed wrt this? If there isn't, :+1:

**Comment by justinvdm** [comment]
Woops, there are docs to remove, will fix, thanks.

**Comment by justinvdm** [comment]
Docs removed, ready for another review.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
