### PR TITLE
API boilerplate

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
Looks good to me. The only thing I can think of is, do we want the version bump script, that changes the version in all the places?

**Comment by justinvdm** [comment]
> Looks good to me. The only thing I can think of is, do we want the version bump script, that changes the version in all the places?

Good question, originally had it in, but decided to leave it out. Some of our other projects like molo seem to automating most of the release process [via travis](https://docs.travis-ci.com/user/deployment/pypi), so all that is needed to add and push a release tag, and travis does the rest. Thinking of using something like that instead.

First wanted to give that part some thought, so decided to leave the way we will be publishing out of this PR.

**Comment by rudigiesler** [comment]
Sounds good 👍  My thought was more the script to bump the versions, rather than the deploying things, since you need to set the versions in multiple places, so it's good to have a script so that you don't forget a place.

I like the tag == release system that molo uses, it's much quicker and takes out a bunch of steps.

**Comment by justinvdm** [comment]
Ah, I was thinking that we could somehow automate the actual version bumping (so all that is needed is a tag), but on second thought, that is probably not going to be easy or worthwhile. Will add a version bumping script to this PR, thanks :)

**Comment by justinvdm** [comment]
Ready for re-review. Went with the version bumping script approach over the `version.json` approach.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
