### PR TITLE
Change GET /.../dialogues/ to return an array

### PR DESCRIPTION
**Pull request by justinvdm**
At the moment it returns a JSON object: `{dialogues: ...}`, but it would make more sense to return an array.

### CODE REVIEW

**Comment by justinvdm** [comment]
Ready for review.

**Comment by hodgestar** [comment]
I sort of like getting back objects consistently at the top level because it gives some indication of what the thing I've gotten back is (which lists are less good for).

I you still prefer this way, :+1: on the changes.

**Comment by justinvdm** [comment]
> I sort of like getting back objects consistently at the top level because it gives some indication of what the thing I've gotten back is (which lists are less good for).

Yep, that was my reasoning for how it was initially. Ended up changing my mind, figured it made more sense that if someone is accessing a collection of resources, they should expect an array and if they are accessing a resource, they should expect an object.

Going to go with this for now, but will give it some more thought.

**Comment by hodgestar** [comment]
Cool. :+1:

**Pull request merged**
